export const SET_USER = 'SET_USER';
export const CREATE_NEW_USER_WATCHER = 'CREATE_NEW_USER_WATCHER';
export const LOGIN_USER_WATCHER = 'LOGIN_USER_WATCHER';
export const RESET_PASSWORD_WATCHER = 'RESET_PASSWORD_WATCHER';
export const PASSWORD_WATCHER = 'RESET_PASSWORD';

export const SET_ERROR = 'SET_ERROR';
